CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE file_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_hash TEXT NOT NULL UNIQUE,
    storage_path TEXT NOT NULL,
    size BIGINT NOT NULL,
    content_type TEXT NOT NULL,
    reference_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    parent_id BIGINT REFERENCES folders(id),
    name TEXT NOT NULL CHECK ( char_length(btrim(name)) > 0 ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_folders_user_parent_name ON folders (user_id, COALESCE(parent_id, 0), name);

CREATE INDEX idx_folders_user_parent ON folders (user_id, parent_id);

CREATE TABLE user_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    parent_id BIGINT REFERENCES folders(id),
    object_id BIGINT REFERENCES file_objects(id),
    original_name TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    size BIGINT NOT NULL,
    content_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_user_files_id_status ON user_files (user_id, status);

CREATE INDEX idx_user_files_object_id ON user_files (object_id);

CREATE INDEX idx_user_files_user_parent_status ON user_files (user_id, parent_id, status);

CREATE TABLE upload_tasks (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    parent_id BIGINT REFERENCES folders(id),
    original_name TEXT NOT NULL,
    content_type TEXT NOT NULL,
    file_size BIGINT NOT NULL CHECK (file_size > 0),
    chunk_size BIGINT NOT NULL CHECK (chunk_size > 0),
    total_chunks INTEGER NOT NULL CHECK (total_chunks > 0),
    file_hash TEXT,
    status TEXT NOT NULL DEFAULT 'uploading'
        CHECK (status IN ('uploading', 'completing', 'completed', 'failed')),
    temp_dir TEXT NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_upload_tasks_user_status ON upload_tasks (user_id, status);

CREATE INDEX idx_upload_tasks_user_parent_status ON upload_tasks (user_id, parent_id, status);

CREATE TABLE upload_chunks (
    upload_id TEXT NOT NULL REFERENCES upload_tasks(id),
    chunk_number INTEGER NOT NULL CHECK (chunk_number >= 0),
    size BIGINT NOT NULL CHECK (size >= 0),
    chunk_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (upload_id, chunk_number)
);

CREATE TABLE file_shares (
    token TEXT PRIMARY KEY CHECK (char_length(token) > 0),
    user_file_id BIGINT NOT NULL REFERENCES user_files(id),
    password_hash TEXT,
    expires_at TIMESTAMPTZ,
    max_downloads INTEGER CHECK (
        max_downloads IS NULL OR max_downloads > 0
    ),
    download_count INTEGER NOT NULL DEFAULT 0 CHECK (download_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (max_downloads IS NULL OR download_count <= max_downloads)
);

CREATE INDEX idx_file_shares_user_file ON file_shares (user_file_id);

CREATE INDEX idx_file_shares_expires_at ON file_shares (expires_at);