CREATE TABLE IF NOT EXISTS share_access_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token TEXT NOT NULL,
    ip_hash TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('info', 'preview', 'download', 'save')),
    result TEXT NOT NULL CHECK (result IN ('allowed', 'denied', 'rate_limited', 'locked')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_share_access_audits_token_created
ON share_access_audits(token, created_at);
